FROM golang:alpine3.19 AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY *.mod *.sum ./
RUN go mod download

COPY . .
RUN rm -f excel_reader

ENV CGO_ENABLED=0
RUN go build -a -o excel_reader ./cmd/readers/excel_reader.go

FROM alpine:latest

RUN apk update && apk add --no-cache bash
WORKDIR /app
COPY --from=builder /app/excel_reader /app/excel_reader
COPY ./files/ /db-files/
CMD ["./excel_reader"]