// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample some AverageRegionIncomes
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)

// GetRegionIncomesAPIRouter defines the required methods for binding the api requests to a responses for the GetRegionIncomesAPI
// The GetRegionIncomesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a GetRegionIncomesAPIServicer to perform the required actions, then write the service results to the http response.
type GetRegionIncomesAPIRouter interface {
	GetRegionIncomes(http.ResponseWriter, *http.Request)
}

// GetRegionIncomesAPIServicer defines the api actions for the GetRegionIncomesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GetRegionIncomesAPIServicer interface {
	GetRegionIncomes(context.Context, int32, int32, int32) (ImplResponse, error)
}
