// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample some AverageRegionIncomes
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// GetRegionIncomesAPIService is a service that implements the logic for the GetRegionIncomesAPIServicer
// This service should implement the business logic for every endpoint for the GetRegionIncomesAPI API.
// Include any external packages or services that will be required by this service.
type GetRegionIncomesAPIService struct {
}

// NewGetRegionIncomesAPIService creates a default api service
func NewGetRegionIncomesAPIService() *GetRegionIncomesAPIService {
	return &GetRegionIncomesAPIService{}
}

// GetRegionIncomes - Get average region incomes
func (s *GetRegionIncomesAPIService) GetRegionIncomes(ctx context.Context, regionid int32, year int32, quarter int32) (ImplResponse, error) {
	// TODO - update GetRegionIncomes with the required logic for this service method.
	// Add api_get_region_incomes_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Averageregionincomes{}) or use other options such as http.Ok ...
	// return Response(200, []Averageregionincomes{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetRegionIncomes method not implemented")
}
