// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample some AverageRegionIncomes
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"github.com/donskova1ex/AverageRegionIncomes/internal/domain"
	"log/slog"
	"net/http"
)
type AverageRegionIncomeProcessor interface {
	GetRegionIncomes(ctx context.Context, regionId int32, year int32, quarter int32) (*domain.AverageRegionIncomes, error)
}
// GetRegionIncomesAPIService is a service that implements the logic for the GetRegionIncomesAPIServicer
// This service should implement the business logic for every endpoint for the GetRegionIncomesAPI API.
// Include any external packages or services that will be required by this service.
type GetRegionIncomesAPIService struct {
	regionIncomesProcessor AverageRegionIncomeProcessor
	log *slog.Logger
}

// NewGetRegionIncomesAPIService creates a default api service
func NewGetRegionIncomesAPIService(averageRegionIncomeProcessor AverageRegionIncomeProcessor, log *slog.Logger ) *GetRegionIncomesAPIService {
	return &GetRegionIncomesAPIService{
		regionIncomesProcessor: averageRegionIncomeProcessor,
		log: log,
	}
}

// GetRegionIncomes - Get average region incomes
func (s *GetRegionIncomesAPIService) GetRegionIncomes(ctx context.Context, regionid int32, year int32, quarter int32) (ImplResponse, error) {
	ri, err := s.regionIncomesProcessor.GetRegionIncomes(ctx, regionid, year, quarter)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}
	openApiRegionIncomes := domainRegionIncomesToOpenApi(ri)
	return Response(http.StatusOK, openApiRegionIncomes), nil
}

func domainRegionIncomesToOpenApi(domainRegionIncomes *domain.AverageRegionIncomes) Averageregionincomes  {
	return Averageregionincomes{
		RegionId: domainRegionIncomes.RegionId,
		Year: domainRegionIncomes.Year,
		Quarter: domainRegionIncomes.Quarter,
		RegionName: domainRegionIncomes.RegionName,
		AverageRegionIncomes: domainRegionIncomes.AverageRegionIncomes,
	}
}
