// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample some AverageRegionIncomes
 *
 * API version: 1.0.0
 */

package openapi

type Averageregionincomes struct {
	RegionId int32 `json:"RegionId,omitempty"`

	RegionName int32 `json:"RegionName,omitempty"`

	Year int32 `json:"Year,omitempty"`

	Quarter int32 `json:"Quarter,omitempty"`

	AverageRegionIncomes float32 `json:"AverageRegionIncomes,omitempty"`
}

// AssertAverageregionincomesRequired checks if the required fields are not zero-ed
func AssertAverageregionincomesRequired(obj Averageregionincomes) error {
	return nil
}

// AssertAverageregionincomesConstraints checks if the values respects the defined constraints
func AssertAverageregionincomesConstraints(obj Averageregionincomes) error {
	return nil
}
