// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample some AverageRegionIncomes
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/donskova1ex/AverageRegionIncomes/openapi"
)

func main() {
	log.Printf("Server started")

	GetRegionIncomesAPIService := openapi.NewGetRegionIncomesAPIService()
	GetRegionIncomesAPIController := openapi.NewGetRegionIncomesAPIController(GetRegionIncomesAPIService)

	router := openapi.NewRouter(GetRegionIncomesAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
