// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/donskova1ex/AverageRegionIncomes/internal/processors (interfaces: AverageIncomeRedisRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/donskova1ex/AverageRegionIncomes/internal/domain"
)

// AverageIncomeRedisRepository is a mock of AverageIncomeRedisRepository interface.
type AverageIncomeRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *AverageIncomeRedisRepositoryMockRecorder
}

// AverageIncomeRedisRepositoryMockRecorder is the mock recorder for AverageIncomeRedisRepository.
type AverageIncomeRedisRepositoryMockRecorder struct {
	mock *AverageIncomeRedisRepository
}

// NewAverageIncomeRedisRepository creates a new mock instance.
func NewAverageIncomeRedisRepository(ctrl *gomock.Controller) *AverageIncomeRedisRepository {
	mock := &AverageIncomeRedisRepository{ctrl: ctrl}
	mock.recorder = &AverageIncomeRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AverageIncomeRedisRepository) EXPECT() *AverageIncomeRedisRepositoryMockRecorder {
	return m.recorder
}

// GetCachedRegionIncomes mocks base method.
	m.ctrl.T.Helper()
	ret0, _ := ret[0].(*domain.AverageRegionIncomes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedRegionIncomes indicates an expected call of GetCachedRegionIncomes.
	mr.mock.ctrl.T.Helper()
}

// SetCachedRegionIncomes mocks base method.
	m.ctrl.T.Helper()
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCachedRegionIncomes indicates an expected call of SetCachedRegionIncomes.
	mr.mock.ctrl.T.Helper()
}
