// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/donskova1ex/AverageRegionIncomes/internal/processors (interfaces: AverageIncomeRedisRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/average_income_redis_repository.go -package=mocks -mock_names=AverageIncomeRedisRepository=AverageIncomeRedisRepository . AverageIncomeRedisRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/donskova1ex/AverageRegionIncomes/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// AverageIncomeRedisRepository is a mock of AverageIncomeRedisRepository interface.
type AverageIncomeRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *AverageIncomeRedisRepositoryMockRecorder
	isgomock struct{}
}

// AverageIncomeRedisRepositoryMockRecorder is the mock recorder for AverageIncomeRedisRepository.
type AverageIncomeRedisRepositoryMockRecorder struct {
	mock *AverageIncomeRedisRepository
}

// NewAverageIncomeRedisRepository creates a new mock instance.
func NewAverageIncomeRedisRepository(ctrl *gomock.Controller) *AverageIncomeRedisRepository {
	mock := &AverageIncomeRedisRepository{ctrl: ctrl}
	mock.recorder = &AverageIncomeRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AverageIncomeRedisRepository) EXPECT() *AverageIncomeRedisRepositoryMockRecorder {
	return m.recorder
}

// GetCachedRegionIncomes mocks base method.
func (m *AverageIncomeRedisRepository) GetCachedRegionIncomes(ctx context.Context, regionId, year, quarter int32) (*domain.AverageRegionIncomes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedRegionIncomes", ctx, regionId, year, quarter)
	ret0, _ := ret[0].(*domain.AverageRegionIncomes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedRegionIncomes indicates an expected call of GetCachedRegionIncomes.
func (mr *AverageIncomeRedisRepositoryMockRecorder) GetCachedRegionIncomes(ctx, regionId, year, quarter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedRegionIncomes", reflect.TypeOf((*AverageIncomeRedisRepository)(nil).GetCachedRegionIncomes), ctx, regionId, year, quarter)
}

// SetCachedRegionIncomes mocks base method.
func (m *AverageIncomeRedisRepository) SetCachedRegionIncomes(ctx context.Context, averageRegionIncomes *domain.AverageRegionIncomes, regionId, year, quarter int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCachedRegionIncomes", ctx, averageRegionIncomes, regionId, year, quarter)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCachedRegionIncomes indicates an expected call of SetCachedRegionIncomes.
func (mr *AverageIncomeRedisRepositoryMockRecorder) SetCachedRegionIncomes(ctx, averageRegionIncomes, regionId, year, quarter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedRegionIncomes", reflect.TypeOf((*AverageIncomeRedisRepository)(nil).SetCachedRegionIncomes), ctx, averageRegionIncomes, regionId, year, quarter)
}
