// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/donskova1ex/AverageRegionIncomes/internal/processors (interfaces: ExcelReaderLogger)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// ExcelReaderLogger is a mock of ExcelReaderLogger interface.
type ExcelReaderLogger struct {
	ctrl     *gomock.Controller
	recorder *ExcelReaderLoggerMockRecorder
}

// ExcelReaderLoggerMockRecorder is the mock recorder for ExcelReaderLogger.
type ExcelReaderLoggerMockRecorder struct {
	mock *ExcelReaderLogger
}

// NewExcelReaderLogger creates a new mock instance.
func NewExcelReaderLogger(ctrl *gomock.Controller) *ExcelReaderLogger {
	mock := &ExcelReaderLogger{ctrl: ctrl}
	mock.recorder = &ExcelReaderLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ExcelReaderLogger) EXPECT() *ExcelReaderLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *ExcelReaderLogger) Error(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *ExcelReaderLoggerMockRecorder) Error(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*ExcelReaderLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *ExcelReaderLogger) Info(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *ExcelReaderLoggerMockRecorder) Info(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*ExcelReaderLogger)(nil).Info), varargs...)
}
