// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/donskova1ex/AverageRegionIncomes/internal/processors (interfaces: ExcelReaderLogger)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/excel_reader_logger.go -package=mocks -mock_names=ExcelReaderLogger=ExcelReaderLogger . ExcelReaderLogger
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// ExcelReaderLogger is a mock of ExcelReaderLogger interface.
type ExcelReaderLogger struct {
	ctrl     *gomock.Controller
	recorder *ExcelReaderLoggerMockRecorder
	isgomock struct{}
}

// ExcelReaderLoggerMockRecorder is the mock recorder for ExcelReaderLogger.
type ExcelReaderLoggerMockRecorder struct {
	mock *ExcelReaderLogger
}

// NewExcelReaderLogger creates a new mock instance.
func NewExcelReaderLogger(ctrl *gomock.Controller) *ExcelReaderLogger {
	mock := &ExcelReaderLogger{ctrl: ctrl}
	mock.recorder = &ExcelReaderLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ExcelReaderLogger) EXPECT() *ExcelReaderLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *ExcelReaderLogger) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *ExcelReaderLoggerMockRecorder) Error(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*ExcelReaderLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *ExcelReaderLogger) Info(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *ExcelReaderLoggerMockRecorder) Info(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*ExcelReaderLogger)(nil).Info), varargs...)
}
