openapi: 3.0.0
info:
  title: Swagger user management service - OpenAPI 3.0
  description: |-
    This is a sample some AverageRegionIncomes 
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: GetRegionIncomes
    description: get region incomes by regionid, year, quarter
paths:
  /regionincomes:
    get:
      tags:
        - GetRegionIncomes
      summary: Get average region incomes
      description: returns average region incomes
      operationId: GetRegionIncomes
      parameters:
        - name: regionid
          in: query
          required: true
          schema:
            type: integer
        - name: year
          in: query
          required: false
          schema:
            type: integer
        - name: quarter
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/averageregionincomes"
        '400':
          description: Invalid dates
        '404':
          description: parameters not found
components: 
  schemas:
    averageregionincomes:
      type: object
      properties: 
        RegionId:
          type: integer
          example: 02
        RegionName:
          type: integer
          example: Республика Башкортостан
        Year:
          type: integer
          example: 2025
        Quarter:
          type: integer
          example: 1
        AverageRegionIncomes:
          type: number
          example: 36587.16
    


